# Generated by Django 5.0.4 on 2024-05-02 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_student_docs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='docs',
        ),
        migrations.RemoveField(
            model_name='student',
            name='standard',
        ),
    ]
